/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package forms;

import java.awt.Desktop;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.net.URI;
import java.time.LocalTime;

/**
 *
 * @author PC
 */
public class jpMainMenu extends javax.swing.JPanel {

    /**
     * Creates new form jpMainMenu
     */
    public jpMainMenu() {
        initComponents();
        

        LocalTime now = LocalTime.now();
        String saludo;
        if (now.isBefore(LocalTime.of(12, 0))) {
            saludo = "BUENOS DIAS!";
        } else if (now.isBefore(LocalTime.of(18, 0))) {
            saludo = "BUENAS TARDES!";
        } else {
            saludo = "BUENAS NOCHES!";
        }
        jlWelcome.setText(saludo);
        jlInfo.setText("<html>\"Brilliant Minds is a comprehensive school management application designed for elementary schools. It allows users to view student profiles, including personal information and academic details. The application enables the creation of new student records, the display of grades for all four academic terms, and provides filtering options to view data by grade and subject. Additionally, Brilliant Minds calculates students' grade averages in real-time and allows modifications to individual grades, offering a streamlined tool for both educators and school administrators.\"</html>");
    
        jlGit.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                try {
                    Desktop.getDesktop().browse(new URI("https://github.com/danielduenasl/Proyecto2_Java"));
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpMarca = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpContent = new javax.swing.JPanel();
        jlWelcome = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlInfo = new javax.swing.JLabel();
        jlImage = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jlGit = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(760, 606));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jpMarca.setBackground(new java.awt.Color(255, 255, 255));
        jpMarca.setPreferredSize(new java.awt.Dimension(760, 32));
        jpMarca.setLayout(new java.awt.BorderLayout());

        jLabel1.setForeground(new java.awt.Color(225, 225, 225));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dalila & Daniel");
        jpMarca.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jpMarca, java.awt.BorderLayout.PAGE_END);

        jpContent.setBackground(new java.awt.Color(255, 255, 255));

        jlWelcome.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jlWelcome.setForeground(new java.awt.Color(0, 0, 0));
        jlWelcome.setText("WELCOME");

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));

        jlInfo.setBackground(new java.awt.Color(255, 255, 255));
        jlInfo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlInfo.setForeground(new java.awt.Color(0, 0, 0));
        jlInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jlImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brilliant_minds (1).jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlImage, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jlInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlImage, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(245, 245, 245));

        jlGit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlGit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brand-github (2).png"))); // NOI18N
        jlGit.setToolTipText("Click to access the User Manual");
        jlGit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlGit, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlGit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jpContentLayout = new javax.swing.GroupLayout(jpContent);
        jpContent.setLayout(jpContentLayout);
        jpContentLayout.setHorizontalGroup(
            jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContentLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpContentLayout.createSequentialGroup()
                        .addComponent(jlWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(186, 186, 186))
                    .addGroup(jpContentLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20))))
        );
        jpContentLayout.setVerticalGroup(
            jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContentLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jlWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addGroup(jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32))
        );

        jPanel1.add(jpContent, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jlGit;
    private javax.swing.JLabel jlImage;
    private javax.swing.JLabel jlInfo;
    private javax.swing.JLabel jlWelcome;
    private javax.swing.JPanel jpContent;
    private javax.swing.JPanel jpMarca;
    // End of variables declaration//GEN-END:variables
}
