/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package forms;

import java.time.LocalTime;

/**
 *
 * @author PC
 */
public class jpMainMenu extends javax.swing.JPanel {

    /**
     * Creates new form jpMainMenu
     */
    public jpMainMenu() {
        initComponents();
        

        LocalTime now = LocalTime.now();
        String saludo;
        if (now.isBefore(LocalTime.of(12, 0))) {
            saludo = "BUENOS DIAS!";
        } else if (now.isBefore(LocalTime.of(18, 0))) {
            saludo = "BUENAS TARDES!";
        } else {
            saludo = "BUENAS NOCHES!";
        }
        jlWelcome.setText(saludo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpMarca = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpContent = new javax.swing.JPanel();
        jlWelcome = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(760, 606));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jpMarca.setBackground(new java.awt.Color(255, 255, 255));
        jpMarca.setPreferredSize(new java.awt.Dimension(760, 32));
        jpMarca.setLayout(new java.awt.BorderLayout());

        jLabel1.setForeground(new java.awt.Color(225, 225, 225));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dalila & Daniel");
        jpMarca.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jpMarca, java.awt.BorderLayout.PAGE_END);

        jpContent.setBackground(new java.awt.Color(255, 255, 255));

        jlWelcome.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jlWelcome.setForeground(new java.awt.Color(0, 0, 0));
        jlWelcome.setText("WELCOME");

        javax.swing.GroupLayout jpContentLayout = new javax.swing.GroupLayout(jpContent);
        jpContent.setLayout(jpContentLayout);
        jpContentLayout.setHorizontalGroup(
            jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContentLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jlWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );
        jpContentLayout.setVerticalGroup(
            jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContentLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jlWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(437, Short.MAX_VALUE))
        );

        jPanel1.add(jpContent, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlWelcome;
    private javax.swing.JPanel jpContent;
    private javax.swing.JPanel jpMarca;
    // End of variables declaration//GEN-END:variables
}
