/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package forms;

import frames.DatosModif;
import java.awt.Color;
import javax.swing.ImageIcon;
import static javax.swing.SwingConstants.CENTER;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author niza
 */
public class jpPromedio extends javax.swing.JPanel {

    /** Creates new form jpPromedio */
    public jpPromedio() {
        initComponents();
        MostarPromedio();
        Aprueba();
        
        txtNota1.getDocument().addDocumentListener(new DocumentListener() {
                @Override
                public void insertUpdate(DocumentEvent e) {
                    MostarPromedio();
                    Aprueba();
                }

                @Override
                public void removeUpdate(DocumentEvent e) {
                    if (!txtNota1.getText().isEmpty()){
                        MostarPromedio();
                        Aprueba();
                    }                
                }

                @Override
                public void changedUpdate(DocumentEvent e) {
                    MostarPromedio();
                    Aprueba();
                }
            });
        txtNota2.getDocument().addDocumentListener(new DocumentListener() {
                @Override
                public void insertUpdate(DocumentEvent e) {
                    MostarPromedio();
                    Aprueba();
                }

                @Override
                public void removeUpdate(DocumentEvent e) {
                    if (!txtNota2.getText().isEmpty()){
                        MostarPromedio();
                        Aprueba();
                    }   
                }

                @Override
                public void changedUpdate(DocumentEvent e) {
                    MostarPromedio();
                    Aprueba();
                }
            });
        txtNota3.getDocument().addDocumentListener(new DocumentListener() {
                @Override
                public void insertUpdate(DocumentEvent e) {
                    MostarPromedio();
                    Aprueba();
                }

                @Override
                public void removeUpdate(DocumentEvent e) {
                    if (!txtNota3.getText().isEmpty()){
                        MostarPromedio();
                        Aprueba();
                    }   
                }

                @Override
                public void changedUpdate(DocumentEvent e) {
                    MostarPromedio();
                    Aprueba();
                }
            });
        txtNota4.getDocument().addDocumentListener(new DocumentListener() {
                @Override
                public void insertUpdate(DocumentEvent e) {
                    MostarPromedio();
                    Aprueba();
                }

                @Override
                public void removeUpdate(DocumentEvent e) {
                    if (!txtNota4.getText().isEmpty()){
                        MostarPromedio();
                        Aprueba();
                    }   
                }

                @Override
                public void changedUpdate(DocumentEvent e) {
                    MostarPromedio();
                    Aprueba();
                }
            });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLTitulo = new javax.swing.JLabel();
        txtNota1 = new models.CustomTextField();
        txtNota2 = new models.CustomTextField();
        txtNota3 = new models.CustomTextField();
        txtNota4 = new models.CustomTextField();
        txtPromedio = new models.CustomTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEstudiante = new models.CustomTextField();
        customComboBox1 = new models.CustomComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCarnet = new models.CustomTextField();
        jpBtnGuardar = new javax.swing.JPanel();
        jlBtnGuardar = new javax.swing.JLabel();
        jpBtnSearch = new javax.swing.JPanel();
        jlBtnSearch = new javax.swing.JLabel();
        jpAprueba = new javax.swing.JPanel();
        jlAprueba = new javax.swing.JLabel();
        jpBtnDM = new javax.swing.JPanel();
        jlBtnDM = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLTitulo.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jLTitulo.setText("CALCULO DE PROMEDIO");

        txtNota1.setForeground(new java.awt.Color(51, 51, 51));
        txtNota1.setText("0");
        txtNota1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtNota1InputMethodTextChanged(evt);
            }
        });
        txtNota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNota1ActionPerformed(evt);
            }
        });

        txtNota2.setForeground(new java.awt.Color(51, 51, 51));
        txtNota2.setText("0");

        txtNota3.setForeground(new java.awt.Color(51, 51, 51));
        txtNota3.setText("0");

        txtNota4.setText("0");
        txtNota4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNota4ActionPerformed(evt);
            }
        });

        txtPromedio.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("NOTA 1");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("NOTA 2");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("NOTA 4");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("PROMEDIO");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("NOTA 3");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("CARNET");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("MATERIA");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("ESTUDIANTE");

        jpBtnGuardar.setBackground(new java.awt.Color(222, 8, 163));
        jpBtnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jpBtnGuardar.setLayout(new java.awt.BorderLayout());

        jlBtnGuardar.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jlBtnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jlBtnGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlBtnGuardar.setText("GUARDAR DATOS");
        jlBtnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlBtnGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlBtnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlBtnGuardarMouseExited(evt);
            }
        });
        jpBtnGuardar.add(jlBtnGuardar, java.awt.BorderLayout.CENTER);

        jpBtnSearch.setBackground(new java.awt.Color(222, 8, 163));
        jpBtnSearch.setForeground(new java.awt.Color(255, 255, 255));
        jpBtnSearch.setLayout(new java.awt.BorderLayout());

        jlBtnSearch.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jlBtnSearch.setForeground(new java.awt.Color(255, 255, 255));
        jlBtnSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlBtnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/searchS.png"))); // NOI18N
        jlBtnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlBtnSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlBtnSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlBtnSearchMouseExited(evt);
            }
        });
        jpBtnSearch.add(jlBtnSearch, java.awt.BorderLayout.CENTER);

        jpAprueba.setBackground(new java.awt.Color(222, 8, 163));
        jpAprueba.setLayout(new java.awt.BorderLayout());
        jpAprueba.add(jlAprueba, java.awt.BorderLayout.CENTER);

        jpBtnDM.setBackground(new java.awt.Color(222, 8, 163));
        jpBtnDM.setForeground(new java.awt.Color(255, 255, 255));
        jpBtnDM.setLayout(new java.awt.BorderLayout());

        jlBtnDM.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jlBtnDM.setForeground(new java.awt.Color(255, 255, 255));
        jlBtnDM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlBtnDM.setText("DATOS MODIFICADOS!");
        jlBtnDM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlBtnDMMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlBtnDMMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlBtnDMMouseExited(evt);
            }
        });
        jpBtnDM.add(jlBtnDM, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(txtCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jpBtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(253, 253, 253)
                                .addComponent(jpBtnDM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jpBtnGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNota1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtEstudiante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNota3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(199, 199, 199)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jpAprueba, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                    .addComponent(txtNota2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(customComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNota4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(32, 32, 32))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtCarnet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                        .addComponent(jpBtnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jpBtnDM, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(customComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNota2, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(txtNota1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNota4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNota3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpBtnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jpAprueba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPromedio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNota4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNota4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNota4ActionPerformed

    private void jlBtnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBtnGuardarMouseClicked

        jpBtnGuardar.setBackground(new Color (222, 8, 163));
    }//GEN-LAST:event_jlBtnGuardarMouseClicked

    private void jlBtnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBtnGuardarMouseEntered
        jpBtnGuardar.setBackground(new Color (232, 50, 22));
    }//GEN-LAST:event_jlBtnGuardarMouseEntered

    private void jlBtnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBtnGuardarMouseExited
        jpBtnGuardar.setBackground(new Color (222, 8, 163));
    }//GEN-LAST:event_jlBtnGuardarMouseExited

    private void jlBtnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBtnSearchMouseClicked
        jpBtnSearch.setBackground(new Color (222, 8, 163));
    }//GEN-LAST:event_jlBtnSearchMouseClicked

    private void jlBtnSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBtnSearchMouseEntered
        jpBtnSearch.setBackground(new Color (232, 50, 22));
    }//GEN-LAST:event_jlBtnSearchMouseEntered

    private void jlBtnSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBtnSearchMouseExited
        jpBtnSearch.setBackground(new Color (222, 8, 163));
    }//GEN-LAST:event_jlBtnSearchMouseExited

    private void txtNota1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtNota1InputMethodTextChanged

    }//GEN-LAST:event_txtNota1InputMethodTextChanged

    private void txtNota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNota1ActionPerformed
        
    }//GEN-LAST:event_txtNota1ActionPerformed

    private void jlBtnDMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBtnDMMouseClicked
        DatosModif DM = new DatosModif();
        DM.show();
        jpBtnDM.setBackground(new Color (222, 8, 163));
    }//GEN-LAST:event_jlBtnDMMouseClicked

    private void jlBtnDMMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBtnDMMouseEntered
        jpBtnDM.setBackground(new Color (232, 50, 22));
    }//GEN-LAST:event_jlBtnDMMouseEntered

    private void jlBtnDMMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBtnDMMouseExited
        jpBtnDM.setBackground(new Color (222, 8, 163));
    }//GEN-LAST:event_jlBtnDMMouseExited

    private void MostarPromedio(){
        float n1 = Float.parseFloat(txtNota1.getText());
        float n2 = Float.parseFloat(txtNota2.getText());
        float n3 = Float.parseFloat(txtNota3.getText());
        float n4 = Float.parseFloat(txtNota4.getText());
        txtPromedio.setText(String.valueOf((n1 + n2 + n3 + n4)/ 4));
    }
    
    private void Aprueba(){
        ImageIcon No = new ImageIcon(getClass().getResource("/images/NoAprob.png"));
        ImageIcon SI = new ImageIcon(getClass().getResource("/images/SiAprob.png"));
        if (Float.parseFloat(txtPromedio.getText()) > 60){
            jlAprueba.setIcon(SI);
            jlAprueba.setHorizontalAlignment(CENTER);
            jlAprueba.setVerticalAlignment(CENTER);
            jpAprueba.setBackground(Color.green);
        } else {
            jlAprueba.setIcon(No);
            jlAprueba.setHorizontalAlignment(CENTER);
            jlAprueba.setVerticalAlignment(CENTER);
            jpAprueba.setBackground(Color.red);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private models.CustomComboBox customComboBox1;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlAprueba;
    private javax.swing.JLabel jlBtnDM;
    private javax.swing.JLabel jlBtnGuardar;
    private javax.swing.JLabel jlBtnSearch;
    private javax.swing.JPanel jpAprueba;
    private javax.swing.JPanel jpBtnDM;
    private javax.swing.JPanel jpBtnGuardar;
    private javax.swing.JPanel jpBtnSearch;
    private models.CustomTextField txtCarnet;
    private models.CustomTextField txtEstudiante;
    private models.CustomTextField txtNota1;
    private models.CustomTextField txtNota2;
    private models.CustomTextField txtNota3;
    private models.CustomTextField txtNota4;
    private models.CustomTextField txtPromedio;
    // End of variables declaration//GEN-END:variables

}
